<?php
/**
 * @file
 * Application logic for the University of Iowa Events module.
 */

 /**
  * Implements hook_permission().
  */
function uiowa_events_permission() {
  return array(
    'administer uiowa events' => array(
      'title' => t('Administer University of Iowa Events'),
      'description' => t('Perform administration tasks for the University of Iowa Events module.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function uiowa_events_menu() {

  $items['events'] = array(
    'title' => 'Events',
    'page callback' => 'uiowa_events_full_listing',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['events/day/%day_date'] = array(
    'title' => 'Day',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['events/week/%week_date'] = array(
    'title' => 'Week',
    'page arguments' => array('week', 2),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  $items['events/month/%month_date'] = array(
    'title' => 'Month',
    'page arguments' => array('month', 2),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  $items['event/%'] = array(
    'page callback' => 'uiowa_events_single_event',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/user-interface/uiowa-events'] = array(
    'title' => 'University of Iowa Events',
    'description' => 'Configuration for the University of Iowa Events module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uiowa_events_config_form'),
    'access arguments' => array('administer uiowa events'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/uiowa_events.admin.inc',
  );

  return $items;
}

/**
 * Load week menu arguments.
 *
 * @param string $arg
 *    The initial argument.
 *
 * @return string
 *    The expected argument.
 */
function week_date_to_arg($arg) {
  if (empty($arg) || $arg == '%') {
    return date('Y-m-d', strtotime('sunday last week'));
  }
  else {
    return date('Y-m-d', strtotime('sunday last week', strtotime($arg)));
  }
}

/**
 * Load month menu arguments.
 *
 * @param string $arg
 *    The initial argument.
 *
 * @return string
 *    The expected argument.
 */
function month_date_to_arg($arg) {
  if (empty($arg) || $arg == '%') {
    return date('Y-m-d', strtotime('first day of this month'));
  }
  else {
    return date('Y-m-d', strtotime('first day of this month', strtotime($arg)));
  }
}

/**
 * Load and return events from Localist.
 *
 * @todo Pass a parameter array in.
 *
 * @param string $days
 *    Return events within this many days after start.
 *    Cannot be used with end.
 * @param string $type
 *    Limit events to filter item IDs.
 * @param string $start
 *    Start of range. Specified as YYYY-MM-DD.
 * @param string $end
 *    End of range, but does not include this date. Specified as YYYY-MM-DD.
 *
 * @return object
 *    A request object.
 */
function uiowa_events_load($days = NULL, $type = NULL, $start = NULL, $end = NULL) {

  $localist_url = "http://events.uiowa.edu/api/2/events";

  $parameters = array(
    'pp' => '50',
  );

  if (!empty($type)) {
    $parameters['type'] = $type;
  }

  if (!empty($start)) {
    $parameters['start'] = $start;
  }

  if (!empty($end)) {
    $parameters['end'] = $end;
  }

  if (!empty($days)) {
    $parameters['days'] = $days;
  }

  $full_url = url($localist_url, array('query' => $parameters));
  return drupal_http_request($full_url);
}

/**
 * Function to display the full listing of events page.
 */
function uiowa_events_full_listing($length = 'day', $date = NULL) {

  if (variable_get('uiowa_events_filter_id')) {
    $type = variable_get('uiowa_events_filter_id');
  }

  $page_date = '';
  if ($date) {
    $page_date = $date;
  }
  else {
    $page_date = date('Y-m-d');
  }

  if (!cache_get('uiowa_events_full_listing_' . $length . "_" . $page_date)) {
    switch ($length) {
      case 'day':
        $localist_events = uiowa_events_load($days = 1, $type, $start = $page_date);
        break;

      case 'week':
        $localist_events = uiowa_events_load($days = 7, $type, $start = $page_date);
        break;

      case 'month':

        $end = date('Y-m-d', strtotime('first day of next month'));

        $localist_events = uiowa_events_load(NULL, $type, $date, $end);
        break;

      default:
        break;
    }

    cache_set('uiowa_events_full_listing_' . $length . "_" . $page_date, $localist_events, 'cache', REQUEST_TIME + (60 * variable_get('uiowa_events_cache_time')));
    $events = json_decode($localist_events->data, TRUE);
  }
  else {
    $return = cache_get('uiowa_events_full_listing_' . $length . "_" . $page_date);
    $events = json_decode($return->data->data, TRUE);
  }

  $data = array();

  foreach ($events['events'] as $event) {
    $new_event = array();
    if (isset($event['event']['id'])) {
      $new_event['id'] = $event['event']['id'];
    }
    if (isset($event['event']['title'])) {
      $new_event['title'] = $event['event']['title'];
    }
    if (isset($event['event']['description'])) {
      $new_event['description'] = $event['event']['description'];
    }
    if (isset($event['event']['event_instances'][0]['event_instance']['start'])) {
      $new_event['start'] = $event['event']['event_instances'][0]['event_instance']['start'];
    }
    if (isset($event['event']['event_instances'][0]['event_instance']['end'])) {
      $new_event['end'] = $event['event']['event_instances'][0]['event_instance']['end'];
    }
    if (isset($event['event']['event_instances'][0]['event_instance']['all_day'])) {
      $new_event['all_day'] = $event['event']['event_instances'][0]['event_instance']['all_day'];
    }
    if (isset($event['event']['photo_url'])) {
      $new_event['photo'] = $event['event']['photo_url'];
    }
    if (isset($event['event']['location'])) {
      $new_event['location'] = $event['event']['location'];
    }
    if (isset($event['event']['room_number'])) {
      $new_event['room_number'] = $event['event']['room_number'];
    }
    array_push($data, $new_event);
  }
  $uiowa_events_path = drupal_get_path('module', 'uiowa_events') . '/includes';
  include_once DRUPAL_ROOT . '/' . $uiowa_events_path . '/uiowa_events.full_listing.inc';
  return theme('uiowa_events_full_listing', array('data' => $data, 'title' => 'Events', 'date' => $page_date));
}

/**
 * Function to display an individual event page.
 */
function uiowa_events_single_event($event_id) {
  // If the configuration is to link out, make all event pages 404.
  if (variable_get('uiowa_events_event_link') == 'event-link-external') {
    drupal_not_found();
  }
  else {
    $localist_url = "http://events.uiowa.edu/api/2/events/" . $event_id;

    if (!cache_get('uiowa_events_single_event' . $event_id)) {
      $localist_event = drupal_http_request($localist_url);
      cache_set('uiowa_events_single_event' . $event_id, $localist_event, 'cache', REQUEST_TIME + (60 * variable_get('uiowa_events_cache_time')));
      $data = json_decode($localist_event->data, TRUE);
    }
    else {
      $return = cache_get('uiowa_events_single_event' . $event_id);
      $data = json_decode($return->data->data, TRUE);
    }
    drupal_add_css(drupal_get_path('module', 'uiowa_events') . '/single.css');
    drupal_add_js(drupal_get_path('module', 'uiowa_events') . '/js/single-event.js');
    $uiowa_events_path = drupal_get_path('module', 'uiowa_events') . '/includes';
    include_once DRUPAL_ROOT . '/' . $uiowa_events_path . '/uiowa_events.single_event.inc';
    return theme('uiowa_events_single_event', array('data' => $data['event'], 'title' => $data['event']['title']));
  }
}

/**
 * Implements hook_theme().
 */
function uiowa_events_theme() {
  $path = drupal_get_path('module', 'uiowa_events') . '/includes';

  $themes = array(
    'uiowa_events_full_listing' => array(
      'path' => $path,
      'file' => 'uiowa_events.full_listing.inc',
      'template' => 'uiowa-events-full-listing',
      'variables' => array('data' => NULL),
    ),
    'uiowa_events_single_event' => array(
      'path' => $path,
      'file' => 'uiowa_events.single_event.inc',
      'template' => 'uiowa-events-single-event',
      'variables' => array('data' => NULL),
    ),
    'uiowa_events_teaser' => array(
      'variables' => array('data' => NULL),
    ),
    'uiowa_events_full_listing_date_nav' => array(
      'variables' => array('date' => NULL),
    ),
  );
  return $themes;
}
